artifacts_directory : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv
  local_save : artifacts/data_ingestion/data.csv
  train_data_path : artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  transformed_train_path: artifacts/data_transformation/X_train_transformed.npy
  transformed_test_path: artifacts/data_transformation/X_test_transformed.npy
  train_target_path: artifacts/data_transformation/y_train.npy
  test_target_path: artifacts/data_transformation/y_test.npy

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/X_train_transformed.npy
  test_data_path: artifacts/data_transformation/X_test_transformed.npy
  train_target_path: artifacts/data_transformation/y_train.npy
  test_target_path: artifacts/data_transformation/y_test.npy
  model_dir: artifacts/model_trainer/models
  cv_folds: 2 # Number of cross-validation folds
  
  model_params:
    LinearRegression:
      fit_intercept: [true, false]
      
    Lasso:
      alpha: [0.001, 0.01, 0.1, 1.0, 10.0]
      max_iter: [1000]
      random_state: [42]
      selection: ['cyclic', 'random']
    
    Ridge:
      alpha: [0.001, 0.01, 0.1, 1.0, 10.0]
      max_iter: [1000]
      random_state: [42]
      solver: ['auto', 'svd', 'cholesky']
    
    SVR:
      kernel: ['linear', 'rbf', 'poly']
      C: [0.1, 1.0, 10.0]
      epsilon: [0.01, 0.1, 0.2]
      gamma: ['scale', 'auto']


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_transformed_path: artifacts/data_transformation/X_test_transformed.npy
  test_target_path: artifacts/data_transformation/y_test.npy
  best_model_path: artifacts/model_trainer/models/best_model.pkl
  evaluation_results_path: artifacts/model_evaluation/evaluation_results.json
  mlflow_uri: "https://dagshub.com/Syam916/mlops.mlflow"